""""
Run Abq from Python
------------------------------------------------------
 Generates the Abq file from the sampled data
    
    - INPUTS: values generated by the sampling that fits into the Kresling
               geometry restrictions in a txt file named '_sampling_data.txt'

               This txt includes by rows the following data:

                n - Sample list with number of polygon sides
                h - Sample list with flat pattern height
                R - List of radius according to the samples generated
              
    - OUTPUTS: Abaqus output files 


"""

import numpy as np

data = np.loadtxt('_sampling_data.txt',delimiter=' ')


for i in range(len(data)-1):
    i = i + 1

    # Parametric data from txt
    n = int(data[i][0])
    R = data[i][1]
    h = data[i][2]
    xH = data[i][3]
    a = data[i][4]
    h3 = data[i][5]
    rho = data[i][6]

    # Additional data
    nMesh = 20
    N = 2
    period = 0.01
    nIntervals = period/50
    thickness = 0.5
    Dist = 5
    materialId = 'TPU'
    folderCAE = '_CAE/'
    step = 'FOLD'

    # Define the file name
    jobName = str(i) + '-' + step + '-n-' + str(n) + '-h-' + str(int(h*100)) + 'e-2'
    print(jobName)

    import _geo2abq
    # Run the main function
    _geo2abq.run(n,R,h, xH, a, h3, rho,jobName,nMesh,period,materialId,N,thickness,folderCAE,step,nIntervals,Dist)
